- src/Routes.tsx
The cloud-services-config file specifies where our app will show up, under /insights/subscriptions/manifests.  That part has been updated in a separate PR in the [cloud-services-config repo](https://github.com/RedHatInsights/cloud-services-config).
Since the ultimate URL we want for this is /insights/subscriptions/manifests (which will be switched to /rhel/subscriptions/manifests post-Summit), we need to change the route for the Satellite Manifest page to render at the application root, which is what this PR changes.
> TEAMNADO-2098 - Change URL for Satellite Manifest component

- README.md
- config/dev.webpack.config.js
- config/prod.webpack.config.js
- package.json
- profiles/local-frontend-and-api.js
- profiles/local-frontend.js
- src/App.js
This updates the app-name from subscription-central to manifests, to align with the config updates.  This will allow for proper functionality of the side menu for the /insights/subscriptions/manifests route on cloud.redhat.com environments, so that the chrome menu app can identify we are on the manifests page and render properly.
Note that the app now also renders, when running locally, at /insights/subscriptions/manifests
> TEAMNADO-2098 updating app name to manifests

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- package.json
insights-chrome (the parent app) adds a class name to the main, based on the "app ID" which in this case, because we are added on top of subscription watch, is 'subscriptions'.  So it creates a `<main class="subscriptions">...</main>`.
Our app, when compiling scss down to css, is adding a root class of `manifests` to "namespace" the app's css. So all scss will get rendered as, e.g., `.manifests h2 { color: #000 }`.    We currently do not have a div with a class of manifests anywhere.  So when this is getting pushed to CI etc., our custom CSS is not being applied.
This fix uses the sassPrefix option provided in [frontend-components-config](https://github.com/RedHatInsights/frontend-components/tree/master/packages/config#readme) to set the sassPrefix  to be `.subscriptions` so that the CSS …
> Fix scss compilation

- src/components/SCAInfoIconWithPopover/SCAInfoIconWithPopover.tsx
Currently, when clicking the Simple Content Access info icon, it triggers a resort.  This adds a fix to prevent the resort.
> Fix bug where clicking popover icon triggers table re-sort

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- src/Routes.tsx
Per conversations with c.rh.c team, the class name of the main component is diverging between beta and stable branches, because the Chrome 2.0 changes have not been deployed to stable environments.  As a result, the CSS is not applying correctly on beta branches.  
This removes a previous sassPrefix fix and wraps the application in a `<div className="manifests"></div>` so that the CSS applies correctly across environments.
We should be able to remove this prefix after Summit, by which point the diverging class names between environments should be resolved.
> Fix app CSS

- src/components/SatelliteManifestPanel/SatelliteManifestPanel.tsx
- src/components/SatelliteManifestPanel/__tests__/__snapshots__/SatelliteManifestPanel.test.tsx.snap
- src/pages/SatelliteManifestPage/__tests__/__snapshots__/SatelliteManifestPage.test.tsx.snap
During demo, Jon Allen recommended that we remove the search bar when is_org_admin is false, and no manifests are found.  
- Updates SatelliteManifestPanel to hide the search bar when is_org_admin is false and no manifests are found.  
- Updates related tests.
> Removing the search bar when no manifests are returned and user is not org admin

- .env
- .env.development
- .env.production
- config/dev.webpack.config.js
- config/prod.webpack.config.js
- package-lock.json
- package.json
- src/hooks/useCreateSatelliteManifest.ts
- src/hooks/useSatelliteManifests.ts
- src/hooks/useSatelliteVersions.ts
Changes: 
- Uses the [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack) module to have environment-specific env files.
- Updates the API base to be pulled in from the respective .env file.
This is shown as an alternative solution to https://github.com/RedHatInsights/subscription-central-ui/pull/15 
Note that from my understanding, the actual NODE_ENV value that determines which .env file to use is being set in the npm scripts, and that currently there is only a development and a production mode.  
If we want a staging mode, we would have to adjust the scripts and probably work with the cloud dot team to update the deployment setup.  I think for now this is fine, since the stage environment is pretty neglected and it seems we will probably also be bypassing it.
> Env-specific config setup

- src/components/ManifestDetailSidePanel/ManifestDetailSidePanel.tsx
- src/components/ManifestDetailSidePanel/__tests__/ManifestDetailSidePanel.test.tsx
- src/components/ManifestDetailSidePanel/__tests__/__snapshots__/ManifestDetailSidePanel.test.tsx.snap
- src/components/SatelliteManifestPanel/__tests__/SatelliteManifestPanel.test.tsx
- src/components/SatelliteManifestPanel/__tests__/__snapshots__/SatelliteManifestPanel.test.tsx.snap
- src/hooks/__tests__/useManifestEntitlements.test.tsx
- src/hooks/useManifestEntitlements.ts
- src/hooks/useSatelliteManifests.ts
Per recent API changes done in [TEAMNADO-2140](https://issues.redhat.com/browse/TEAMNADO-2140), this updates the app to replace the property `contentAccessMode` with `simpleContentAccess`.
> replacing contentAccessMode with simpleContentAccess throughout App

- src/hooks/__tests__/useUpdateManifestSCAStatus.test.tsx
- src/hooks/useUpdateManifestSCAStatus.ts
In the scenario in which the details side panel is open, and then a user clicks the SCA toggle switch, this PR fixes the UI so that the details side panel's SCA status is also updated.
> TEAMNADO-1993 - Fix to update side panel's SCA status

- src/components/SatelliteManifestPanel/SatelliteManifestPanel.tsx
- src/components/SatelliteManifestPanel/__tests__/SatelliteManifestPanel.test.tsx
- src/components/SatelliteManifestPanel/__tests__/__snapshots__/SatelliteManifestPanel.test.tsx.snap
- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
When deleting the final notification, the success toast notification was not being rendered because the entire manifest panel was being replaced by a blank state before the notification could be created.  This moves the blank state into the same component as the delete modal to prevent that.
> Fix delete notification for last manifest

- src/components/CreateManifestModal/CreateManifestModal.tsx
Ref: https://issues.redhat.com/browse/TEAMNADO-2457
After a refactor, it appears there was a minor regression, where, if the create manifest hook is "successful" but with a non-200 response, the Create Manifest Modal form will reset back to the empty form, rather than show the error toast notification. This fixes that issue.
Steps to reproduce current bug: 
1. Go to the app
2. In the useCreateSatelliteManifests hook, change the conditional check for response.status to be something other than 200, say, 2000, just to simulate the error being thrown.
3. With the current branch you will see the form reset. With this branch, the form will properly close the modal and display the toast notification.
> Bugfix: Error message not properly displayed if create manifest hook does not get 200 back

- package-lock.json
- package.json
This updates url-parse to version 1.5.3 to resolve a [security vulnerability](https://issues.redhat.com/browse/TEAMNADO-2696) found in versions below that.
> Update url-parse to 1.5.3 from 1.5.1

- src/components/SCAInfoIconWithPopover/SCAInfoIconWithPopover.tsx
- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
Where links to Insights, Console, Cost & Subscriptions docs exist, this PR updates the url to the 2023 version
> update docs urls to 2023

- src/AppEntry.js
Since Subscriptions manifest can be now in two places we have to adjust the basename to properly be set if in insights bundle we're going to remove 3 items from the pathname, however if in subs bundle we'll remove just 2 items.
> Adjust basename by checking if insights is in href

- jest.setup.js
- package-lock.json
- src/components/Authentication/Authentication.tsx
- src/components/CreateManifestButtonWithModal/__tests__/CreateManifestButtonWithModal.test.tsx
- src/hooks/__tests__/useCreateSatelliteManifest.test.tsx
- src/hooks/__tests__/useDeleteSatelliteManifest.test.tsx
- src/hooks/__tests__/useExportSatelliteManifest.test.tsx
- src/hooks/__tests__/useManifestEntitlements.test.tsx
- src/hooks/__tests__/useSatelliteManifests.test.tsx
- src/hooks/__tests__/useSatelliteVersions.test.tsx
- src/hooks/__tests__/useUpdateManifestSCAStatus.test.tsx
- src/hooks/__tests__/useUser.test.tsx
- src/hooks/useCreateSatelliteManifest.ts
- src/hooks/useDeleteSatelliteManifest.ts
- src/hooks/useExportSatelliteManifest.ts
- src/hooks/useManifestEntitlements.ts
- src/hooks/useSatelliteManifests.ts
- src/hooks/useSatelliteVersions.ts
- src/hooks/useUpdateManifestSCAStatus.ts
- src/hooks/useUser.ts
- src/pages/NoPermissionsPage/NoPermissionsPage.js
- src/pages/NoPermissionsPage/__tests__/NoPermissionsPage.test.tsx
- src/pages/OopsPage/OopsPage.js
- src/pages/OopsPage/__tests__/OopsPage.test.tsx
- src/pages/SatelliteManifestPage/__tests__/SatelliteManifestPage.test.tsx
- src/utilities/__tests__/platformServices.test.ts
- src/utilities/platformServices.ts
This updates all instances of window.insights.chrome to useChrome(). It
touches basically everything because the token is retrieved from the
chroming. To combat this in the future, I have created a custom hook,
useToken so that if (when) the platform changes how this works we won't
have to change nearly as many things.
> TEAMNADO-4959: Migrate to useChrome

- src/components/CreateManifestButtonWithModal/CreateManifestButtonWithModal.tsx
- src/components/CreateManifestButtonWithModal/__tests__/CreateManifestButtonWithModal.test.tsx
- src/components/NoSatelliteSubs/NoSatelliteSubs.tsx
- src/components/NoSatelliteSubs/__tests__/NoSatelliteSubs.test.tsx
- src/components/NoSatelliteSubs/index.tsx
- src/hooks/__tests__/useUser.test.tsx
- src/hooks/useUser.ts
- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
- src/pages/SatelliteManifestPage/__tests__/SatelliteManifestPage.test.tsx
- src/utilities/consts.ts
- src/utilities/factories/user.ts
This adds a gate for manifest creation based on whether or not the user
has a satellite subscription. This is checked via whether or not the
user is entitled to smart_management.
When the user is entitled, the application functions the same as it has
previously. In the case that the user is _not entitled_, yet has
manifests, they should still be able to manage preexisting, but not
create new, manifests. In the case the user is _not entitled_ and has
_no manifests_ they should receive a friendly empty state that directs
them to support, and their subscriptions.
> Teamnado 5960: Add manifest creation gate via chrome.auth.user.entitlements

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- src/AppEntry.js
This removes the nested `BrowserRouter` to support the platform's upgrade to React Router v6
> TEAMNADO-6479: Remove nested `BrowserRouter`

- src/components/ManifestDetailSidePanel/ManifestDetailSidePanel.tsx
- src/components/ManifestEntitlementsList/ManifestEntitlementsList.tsx
- src/components/ManifestEntitlementsList/__tests__/ManifestEntitlementsList.test.tsx
- src/components/SCAInfoIconWithPopover/SCAInfoIconWithPopover.tsx
This changes all instances of subscription allocation to manifest in the content of the page. This does not change references to allocations in function or variable names.
> TEAMNADO-6259: Replace "subscription allocation" with "manifest"

- package.json
- src/hooks/useUser.ts
- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
Manifests users are redirected to the no permissions page when they are unable to read them
> TEAMNADO-7163: Redirect manifests users

- .github/dependabot.yml
- package-lock.json
- package.json
This updates the react testing library to the newest version that still supports react 17. It also adds an ignore clause to dependabot to not attempt to push this dependency to a version that doesn't support React 17.
> Update @testing-library/react to 14.3.1
