RedHatInsights/subscription-central-ui

- src/App.js
> Fix invalid navigation listener.

- package-lock.json
- package.json
Resolves [this issue](https://issues.redhat.com/browse/TEAMNADO-2737).
> TEAMNADO-2737 Forcing latest version of axios to resolve reported vulnerability

- ARCHITECTURE.md
- NAVIGATION.md
- README.md
Updating docs to include information on navigation configuration, as well as detailing app's tooling and architecture.
> Updating Docs

- src/components/SatelliteManifestPanel/__tests__/SatelliteManifestPanel.test.tsx
- src/components/SatelliteManifestPanel/__tests__/__snapshots__/SatelliteManifestPanel.test.tsx.snap
- src/components/SatelliteManifestPanel/satelliteManifestPanelUtils.tsx
Replace SCA toggle switch with plain text when user does not have write permissions.
> Remove sca toggle for read-only users

- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
- src/pages/SatelliteManifestPage/__tests__/__snapshots__/SatelliteManifestPage.test.tsx.snap
This PR adds a learn more link to manifests index page
[TEAMNADO-3068](https://issues.redhat.com/browse/TEAMNADO-3068)
> TEAMNADO-3068 - Add learn more link to manifests

- src/components/ManifestDetailSidePanel/ManifestDetailSidePanel.scss
- src/components/ManifestDetailSidePanel/ManifestDetailSidePanel.tsx
- src/components/ManifestDetailSidePanel/__tests__/__snapshots__/ManifestDetailSidePanel.test.tsx.snap
- src/components/ManifestEntitlementsList/ManifestEntitlementsList.scss
- src/components/ManifestEntitlementsList/ManifestEntitlementsList.tsx
- src/components/ManifestEntitlementsList/__tests__/__snapshots__/ManifestEntitlementsList.test.tsx.snap
- src/components/ManifestEntitlementsList/__tests__/__snapshots__/ManifestEntitlementsListContainer.test.tsx.snap
- src/components/SatelliteManifestPanel/SatelliteManifestPanel.scss
- src/components/SatelliteManifestPanel/SatelliteManifestPanel.tsx
- src/components/SatelliteManifestPanel/__tests__/__snapshots__/SatelliteManifestPanel.test.tsx.snap
- src/pages/SatelliteManifestPage/__tests__/__snapshots__/SatelliteManifestPage.test.tsx.snap
Jira: https://issues.redhat.com/browse/RHCLOUD-17406
- Add "sub" prefix to classes
- Use PF/Platform class naming convention
- add PF variables
> Rescope classes

- src/components/SatelliteManifestPanel/__tests__/__snapshots__/SatelliteManifestPanel.test.tsx.snap
> snapshot missing

- .eslintrc.yml
- src/components/ManifestEntitlementsList/ManifestEntitlementsList.scss
- src/components/ManifestEntitlementsList/ManifestEntitlementsList.tsx
- src/components/ManifestEntitlementsList/ManifestEntitlementsListContainer.tsx
- src/components/ManifestEntitlementsList/__tests__/ManifestEntitlementsList.test.tsx
- src/components/ManifestEntitlementsList/__tests__/__snapshots__/ManifestEntitlementsList.test.tsx.snap
- src/components/ManifestEntitlementsList/__tests__/__snapshots__/ManifestEntitlementsListContainer.test.tsx.snap
- src/components/SatelliteManifestPanel/SatelliteManifestPanel.scss
- src/components/SatelliteManifestPanel/SatelliteManifestPanel.tsx
- src/components/SatelliteManifestPanel/__tests__/__snapshots__/SatelliteManifestPanel.test.tsx.snap
- src/components/SatelliteManifestPanel/__tests__/satelliteManifestPanelUtils.test.tsx
- src/components/SatelliteManifestPanel/satelliteManifestPanelUtils.tsx
- src/hooks/__tests__/useCreateSatelliteManifest.test.tsx
- src/hooks/__tests__/useDeleteSatelliteManifest.test.tsx
- src/hooks/__tests__/useExportSatelliteManifest.test.tsx
- src/hooks/__tests__/useManifestEntitlements.test.tsx
- src/hooks/__tests__/useSatelliteManifests.test.tsx
- src/hooks/__tests__/useSatelliteVersions.test.tsx
- src/hooks/__tests__/useUpdateManifestSCAStatus.test.tsx
- src/hooks/__tests__/useUser.test.tsx
- src/hooks/useCreateSatelliteManifest.ts
- src/hooks/useDeleteSatelliteManifest.ts
- src/hooks/useExportSatelliteManifest.ts
- src/hooks/useManifestEntitlements.ts
- src/hooks/useSatelliteManifests.ts
- src/hooks/useSatelliteVersions.ts
- src/hooks/useUpdateManifestSCAStatus.ts
- src/hooks/useUser.ts
- src/pages/SatelliteManifestPage/__tests__/__snapshots__/SatelliteManifestPage.test.tsx.snap
> Release 3895 4008 to prod stable

- src/components/SCAInfoIconWithPopover/SCAInfoIconWithPopover.scss
Icon size adjustment to medium sized
> Changes to make icon medium

- src/components/SatelliteManifestPanel/SatelliteManifestPanel.tsx
- src/components/SatelliteManifestPanel/__tests__/satelliteManifestPanelUtils.test.tsx
- src/components/SatelliteManifestPanel/satelliteManifestPanelUtils.tsx
- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
- src/pages/SatelliteManifestPage/__tests__/__snapshots__/SatelliteManifestPage.test.tsx.snap
Fixed where name was being passed, but UUID was expected. Delete from Kaba now works
> Teamnado-4020: Inline deletion manifest title is undefined and deletion fails

- build_deploy.sh
- package.json
- pr_check.sh
Add deploy and pr check to sub central
> TEAMNADO-3893 

- src/components/SatelliteManifestPanel/SatelliteManifestPanel.tsx
I have added the Event param to the onChange event as accommodations needed with the PF upgrade. This will indeed fix error flaw of console error with previous merge of package upgrades.
> "Added event param to onChange event to fix bug" promote to "main"

- config/dev.webpack.config.js
part of [RHCLOUD-25607](https://issues.redhat.com/browse/RHCLOUD-25607) . Need to change AppUrl in each of the subscriptions apps to be /subscriptions/ instead of /insights/subscriptions/
> add url for new subs bundle

- src/components/CreateManifestButtonWithModal/CreateManifestButtonWithModal.tsx
- src/components/CreateManifestButtonWithModal/__tests__/CreateManifestButtonWithModal.test.tsx
- src/components/NoSatelliteSubs/NoSatelliteSubs.tsx
- src/components/NoSatelliteSubs/__tests__/NoSatelliteSubs.test.tsx
- src/components/NoSatelliteSubs/index.tsx
- src/hooks/__tests__/useUser.test.tsx
- src/hooks/useUser.ts
- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
- src/pages/SatelliteManifestPage/__tests__/SatelliteManifestPage.test.tsx
- src/utilities/consts.ts
- src/utilities/factories/user.ts
Reverts RedHatInsights/subscription-central-ui#197
This undoes the last revert :-)
> Revert "Update image"

- src/components/SCAInfoIconWithPopover/SCAInfoIconWithPopover.tsx
This story updates the sca info link to direct to the appropriate resource
> "TEAMNADO-7547-Update manifests SCA Link "

- config/prod.webpack.config.js
This can wait to go out until after Konflux is finished but can go ahead and be reviewed
> remove beta build

- src/pages/SatelliteManifestPage/SatelliteManifestPage.tsx
I missed a link that we need to update.
> Update the Manifests learn more link to docs.redhat.com version

- .tekton/subscription-central-ui-pull-request.yaml
- .tekton/subscription-central-ui-push.yaml
adding rpms signature scan to pull request and push yamls
No testing needed.
> TEAMNADO-7821 adding rpms signature scan to tekton pipeline

- .tekton/subscription-central-ui-pull-request.yaml
- .tekton/subscription-central-ui-push.yaml
https://issues.redhat.com/browse/KONFLUX-2264
> Add shell and unicode sast pipeline tasks

- deploy/frontend.yaml
- package-lock.json
- package.json
This shifts the manifests search/navigation/module definitions from chrome-service-backend to this application.
> TUSC-203: Add FEO config for manifests
